plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\yangc\\Desktop\\YCLA_agent\\YCLarch_web"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]